packages:
  - "apps/*"
  - "packages/*"

overrides:
  decode-uri-component: ^0.5.0
  minio>stream-json: link:packages/stream-json-compat
  uuid: ^11.1.1

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  cpu-features: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  protobufjs: true
  ssh2: true
  unrs-resolver: true

onlyBuiltDependencies:
  - esbuild
  - msgpackr-extract
  - "@swc/core"
